minimum_pre_commit_version: '3.7.0'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-shellcheck
    rev: v0.10.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.56.0
    hooks:
      - id: golangci-lint
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        files: \.(c|cc|cpp|cxx|h|hpp)$
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy -p user
        language: system
        files: \.(c|cc|cpp|cxx|h|hpp)$
      - id: check-sources
        name: check-allowed-sources
        entry: tools/check_allowed_sources.py
        language: python
        pass_filenames: false

