######################################################################
##                
## Copyright (C) 2003-2004, 2007,  Karlsruhe University
##                
## File path:     config.mk.in
## Description:   Configuration settings for current build
##                
## Redistribution and use in source and binary forms, with or without
## modification, are permitted provided that the following conditions
## are met:
## 1. Redistributions of source code must retain the above copyright
##    notice, this list of conditions and the following disclaimer.
## 2. Redistributions in binary form must reproduce the above copyright
##    notice, this list of conditions and the following disclaimer in the
##    documentation and/or other materials provided with the distribution.
## 
## THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
## ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
## IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
## ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
## FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
## DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
## OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
## HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
## LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
## OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
## SUCH DAMAGE.
##                
## $Id: config.mk.in,v 1.13 2006/10/21 04:08:17 reichelt Exp $
##                
######################################################################

# Generated by configure script

ARCH=		amd64
PLAT=           amd64-pc99
KERNEL=		x86-kernel

prefix=		/usr/local
exec_prefix=	/usr/local
includedir=	/usr/local/include
libdir=		/usr/local/lib/l4
libexecdir=	/usr/local/libexec/l4
kerneldir=	../kernel


SHELL=		/bin/sh
CC=		cc
CXX=		$(CC) -x c++
AS=		$(CC)
CFLAGS=		-std=c2x
CXXFLAGS=       $(CXXSTD) -fno-exceptions
CXXSTD=	-std=c++23
LDFLAGS=	
CPPFLAGS=	
LGCC=		-lgcc

TOOLPREFIX=	
AR=		$(TOOLPREFIX)ar
RANLIB=		$(TOOLPREFIX)ranlib
LD=		$(TOOLPREFIX)ld
OBJCOPY=	$(TOOLPREFIX)objcopy
RMDIR=		rmdir
LN_S=		ln -s
AUTOCONF=	autoconf
MKDIRHIER=	$(top_srcdir)/../tools/mkdirhier
AWK=		awk

INSTALL=	install
INSTALL_PROGRAM=install
INSTALL_DATA=	install -m 644
INSTALL_SCRIPT=	install

KICKSTART_LINKBASE=	0
SIGMA0_LINKBASE=	0
ROOTTASK_LINKBASE=	0
