name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-userland:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential
      - name: Install Python tools
        run: |
          python3 -m pip install --user pre-commit compiledb configuredb
          pre-commit --version
          compiledb --version
          configuredb --help
      - name: Configure userland
        run: |
          mkdir build
          cd build
          ../user/configure
      - name: Build userland
        run: |
          cd build
          make -j$(nproc)
      - name: Run tests
        run: |
          pip install pytest
          pytest tests/test_subdomain.py

  build-kernel:
    runs-on: ubuntu-latest
    needs: build-userland
    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential
      - name: Install Python tools
        run: |
          python3 -m pip install --user pre-commit compiledb configuredb
          pre-commit --version
          compiledb --version
          configuredb --help
      - name: Build kernel
        run: |
          make -C kernel BUILDDIR=$PWD/kernel-build
          cd kernel-build
          make -j$(nproc)
      - name: Archive kernel image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: kernel-build/*-kernel

  build-kernel-x16:
    runs-on: ubuntu-latest
    needs: build-userland
    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential m16c-elf-gcc
      - name: Build kernel (i16)
        run: |
          make -C kernel BUILDDIR=$PWD/kernel-i16 TOOLPREFIX=m16c-elf- ARCH=i16 SUBARCH=x16
          cd kernel-i16
          make -j$(nproc)
