name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-userland:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install build tools
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential
    - name: Configure userland
      run: |
        mkdir build
        cd build
        ../user/configure
    - name: Build userland
      run: |
        cd build
        make -j$(nproc)
